### ISSUE TITLE
PHP "non-object"

### ISSUE THREAD

**Issue by iceblade112** [mozilla/browserid-cookbook#44]
Using the cookbook's PHP example, there'll be an infinite reload.
I've tried with/without "cacert.pem".

![ss](https://f.cloud.github.com/assets/1739197/2143178/ab0fa892-936e-11e3-897b-6740e8b4c19b.png)

Also happens on lighttpd (same error and reload).

**Comment by smithb1994** [comment]
I believe this is due to the fact you are using localhost... I could be wrong though.
Did you ever find a solution to this?

**Comment by smithb1994** [comment]
I fixed this bug by changing the CURLOPT_SSL_VERIFYPEER to false in the persona.php file.
See the readme.txt file for more details about windows users.

**Comment by iceblade112** [comment]
@smithb1994 - That's rather funny...
It didn't work on my Ubuntu-based server either. Okay, thanks though!
